site_name: SwarmSync Documentation
nav:
  - Home: index.md
  - Getting Started: get-started/quick-start-manage-dji-drones.md
  - Integrations: integrations/dji-platform-integrations.md
  - API Reference: reference/api-reference.md
theme: material